# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'StatusAlert', '~> 1.1.1'
  pod 'IHKeyboardAvoiding'
  pod 'DynamicCodable', '1.0'
  pod 'ILG'

end
