insert into fine.stocks (symbol, name, sector, industry, location, source, cik) values
("HEXO","Hexo","Health Care","Pharmaceuticals","Gatineau, Quebec","favorites","0001690947"),
("CGC","Capony Growth","Health Care","Pharmaceuticals","Smiths Falls, Ontario","favorites","0001737927"),
("ACB","Aurora Cannabis","Health Care","Pharmaceuticals","Edmonton, Alberta","favorites","0001683541"),
("CRON","Cronos Group","Health Care","Pharmaceuticals","Toronto, Ontario","favorites","0001656472"),
("BYND","Beyond Meat","Consumer Staples","Food Products","El Segundo, California","favorites","0001655210"),
("TSLA","Tesla Inc.","Consumer Discretionary","Automobiles","Palo Alto, California","favorites","0001318605"),
("UBER","Uber Technologies, Inc", "Industrials", "Road & Rail", "San Francisco, California", "favorites","0001543151"),
("LYFT","Lyft, Inc.", "Industrials", "Road & Rail", "San Francisco, California", "favorites","0001759509"),
("BABA","Alibaba Group Holding Ltd","Consumer Discretionary","Internet & Direct Marketing Retail","Hangzhou, Hong Kong","favorites","0001577552"),
("TWLO","Twilio","Information Technology", "IT Services", "San Francisco, California", "favorites","0001447669"),
("SQ","Square","Information Technology", "IT Services", "San Francisco, California","favorites","0001512673"),
("VWDRY","Vestas Wind Systems", "Industrials", "Electrical Equipment", "Aarhus, Denmark","favorites",""),
("FSLR","First Solar","Information Technology", "Semiconductors & Semiconductor Equipment","Tempe, Arizona","favorites","0001274494"),
("ENPH","Enphase Energy","Industrials","Electrical Equipment","Fremont, California","favorites","0001463101"),
("SPWR","SunPower","Information Technology", "Semiconductors & Semiconductor Equipment","San Jose, California","favorites","0000867773"),
("MGTX","MeiraGTx","Health Care", "Biotechnology", "New York, New York", "favorites","0001735438");
